### ISSUE TITLE
Cannot access the REST api on Android

### ISSUE THREAD

**Issue by omarzia88** [knowgoio/knowgo-vehicle-simulator#6]
I have installed the simulator on an android phone, But when I am trying to access it from my laptop using my phone's IP , I cannot access it, Can you help me figure this thing out.?Should I use port 8086 while accessing the android version?

**Comment by pmundt** [comment]
Yes, this is the correct port to use on Android. It works ok for me in the simulator, but I will try it on a real device and see if I can reproduce. It's possible there is a permission inconsistency between the debug and release builds.

**Comment by omarzia88** [comment]
Thanks, 
Please update the release builds if you can figure out the problem

**Comment by pmundt** [comment]
Ok, I finally had a chance to follow this up. The problem turned out to be that binding to localhost on Android doesn't expose the port on the other interfaces, so I have now changed this to bind by default to all network interfaces (this can still be overridden for people who do not want this behaviour). I'll push this out to git now, and will make a new release to the app store in the coming days.
